version: '3.8'
services:
    db:
        image: postgres:13
        container_name: db
        restart: always
        ports:
            - "5432:5432"
        expose:
            - "5432"
        volumes:
            - "./postgresql:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=discordbot
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - bot-network

    bot:
        build: .
        container_name: bot
        restart: always
        volumes:
            - ".:/opt/DiscordBot"
        depends_on:
            - "db"
        networks:
            - bot-network

networks:
    bot-network:
        driver: bridge
