version: '3'
services:
    db:
        image: postgres
        container_name: db
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - /opt/pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
    bot:
        build: .
        container_name: bot
        restart: always
        env_file: .env
        depends_on:
            - "db"
